= Install Pulsar Admin Console on Server/VM

:page-tag: luna-streaming,dev,install,admin,pulsar

The Pulsar Admin Console has two main components: 

* A Node.js application that runs the server and serves the dashboard client code to browsers. 
* An NGINX server that routes network traffic to different locations within the Pulsar Cluster. 

Technically, the two processes do not need to be collocated, but we recommend running them on the same host/virtual machine (VM).

== Install Pulsar Admin Console

. Download and install the Node version 11.15.0 tarball to the VM. You can find the most recent Node release https://nodejs.org/en/download/[here].

----
wget https://nodejs.org/dist/v11.15.0/node-v11.15.0-linux-x64.tar.xz / 
tar -xf node-v11.15.0-linux-x64.tar.xz
----
[start=2]
. Download and install the Pulsar Admin console tarball to the VM. You can find the most recent Pulsar Admin Console release https://github.com/datastax/pulsar-admin-console/releases[here].

----
wget https://github.com/datastax/pulsar-admin-console/releases/download/1.1.5/pulsar-admin-console-1.1.5.tar.gz
----

[start=3]
. Decompress and unzip the tarball in the desired location.

----
tar -xf pulsar-admin-console-1.1.5.tar.gz
----
[start=4]
. This will create a `dest/` directory that contains all necessary dependencies for the Pulsar Admin Console (except node).
. From `dest/server`, run `npm start` to start up the Pulsar Admin Console. By default, this will start the server running listening at `localhost:6454`.

== Modify Admin Console Configuration

You can modify the configuration for the console in `dest/dashboard/dest/config.js`. 

Alternatively, you can override configuration values by creating a file named `config-override.js` in the `dest/dashboard/dest/` directory. See below for an example:

----
var globalConf = {
    	"template_directory_uri": "",
    	"ajax_url": "",
    	"rest_url": "",
    	"tenant": "{{ .Values.pulsarAdminConsole.defaultTenant }}",
    	"polling_interval": "10000",
    	"wss_url": "",
    	"disable_billing": "",
    	"home_cluster": "{{ template "pulsar.fullname" . }}",
    	"test": "",
    	"client_token": "",
    	"admin_token": "",
    	"login": "admin",
    	"email": "",
    	"client_role": "",
    	"plan": "",
    	"need_to_create_plan": "",
    	"plan_to_create": "",
    	"admin_role": "",
    	"cluster_list": [],
    	"api_base_url": "",
    	"ca_certificate": "",
    	"api_version": "”,
    	"default_plan": "",
    	"notice_text": "",
    	"grafana_url": "”,
    	"user_role": "administrator",
    	"feature_flags": {
        	"function": true,
        	"sink": true,
        	"source": true,
        	"tenantStats": false
    	},
    	"security": "",
    	"chargebee_site": "",
    	"billing_provider": "",
    	"multi_user_org": "",
    	"private_org": "true",
    	"functions_disabled": "false",
    	"clients_disabled": "false",
    	"running_env": "k8s",
    	"use_token_list": "false",
    	"auth_mode": "",
    	"oauth_client_id": "",
    	"host_overrides": {
        	"pulsar": "",
        	"ws": "”,
        	"http": "”
    	}
	}
----

== Install Nginx

You must install nginx on the same host. You can find installation instructions https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/[here].

It’s essential to configure Nginx to route traffic appropriately with the configuration file in `/etc/nginx/nginx.conf` file. In the sample configuration below, there are comments for each section to help decide how to build the `nginx.conf` file:

=== Sample nginx.conf
----
worker_processes  3;
error_log  /var/log/nginx/error.log;
pid        /tmp/nginx.pid;
events {
 worker_connections  10240;
}
http {
 proxy_temp_path /tmp/proxy_temp;
 client_body_temp_path /tmp/client_temp;
 fastcgi_temp_path /tmp/fastcgi_temp;
 uwsgi_temp_path /tmp/uwsgi_temp;
 scgi_temp_path /tmp/scgi_temp;

 log_format  main
         'remote_addr:$remote_addr\t'
         'time_local:$time_local\t'
         'method:$request_method\t'
         'uri:$uri\t'
         'host:$host\t'
         'status:$status\t'
         'bytes_sent:$body_bytes_sent\t'
         'referer:$http_referer\t'
         'useragent:$http_user_agent\t'
         'forwardedfor:$http_x_forwarded_for\t'
         'request_time:$request_time';
 access_log        /var/log/nginx/access.log main;

 upstream backend {
   server localhost:6454;
 }

 # Only required if running with HTTP
 upstream http-pulsar-proxy {
   server <<Pulsar HTTP Proxy DNS Entry and Port>>;
 }

 # Only required if running with HTTPS
 upstream https-pulsar-proxy {
   server <<Pulsar HTTPS Proxy DNS Entry and Port>>;
 }

 # Only required if running Pulsar Burnell
 # Burnell is meant to run collocated with the Pulsar Proxy and the Pulsar Websocket Proxy
 # https://github.com/datastax/burnell
 upstream pulsar-burnell {
   server <<Pulsar Burnell DNS Entry and Port>>;
 }

 # Only required if running websocket on Pulsar Proxy
 # Should target either the ws or the wss port depending on the upstream scheme
 upstream ws-pulsar-proxy {
   server <<Pulsar Websocket Proxy DNS Entry and Port>>
 }

 ## Only required if using Open ID Connect for authenticating the Pulsar Admin Console
 upstream identity-provider {
    server <<Identity Provider DNS Entry and Port>>;
 }

 # For all location blocks, use the correct scheme for upstream targets
 server {

       location /ruok {
         access_log off;
         return 200 "I'm good\n";
       }

       # Routes traffic to the Pulsar Admin Console server
       location / {
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass_header Set-Cookie;
          proxy_pass http://backend;
       }

       # Routes traffic to the websocket proxy
       location /ws/ {
         # Use https or http depending on configuration
         proxy_pass https://ws-pulsar-proxy;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "Upgrade";
         proxy_set_header Host $host;
       }

       # General cluster forwarding rule for functions
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v1/<<Pulsar cluster name>>/functions {
         proxy_set_header Accepts application/json;
         rewrite ^/api/v1/<<Pulsar cluster name>>/functions/(.*)$ /admin/v3/functions/$1 break;
         proxy_pass http://http-pulsar-proxy$uri$is_args$args;
       }

       # Cluster forwarding rule for sinks
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v1/<<Pulsar cluster name>>/sinks {
         rewrite ^/api/v1/<<Pulsar cluster name>>/sinks/(.*)$ /admin/v3/sinks/$1 break;
         proxy_pass http://http-pulsar-proxy$uri$is_args$args;
       }

       # Cluster forwarding rule for sources
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v1/<<Pulsar cluster name>>/sources {
         rewrite ^/api/v1/<<Pulsar cluster name>>/sources/(.*)$ /admin/v3/sources/$1 break;
         proxy_pass http://http-pulsar-proxy$uri$is_args$args;
       }

       # Cluster forwarding rule for Burnell
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v2/<<Pulsar cluster name>>/br/ {
         rewrite ^/api/v2/<<Pulsar cluster name>>/br/(.*)$ /$1 break;
         proxy_pass https://pulsar-burnell$uri$is_args$args;
       }

       # Forwarding rule api v2 (Burnell)
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v2/<<Pulsar cluster name>> {
         rewrite ^/api/v2/<<Pulsar cluster name>>/(.*)$ /admin/v2/$1 break;
         proxy_pass http://pulsar-burnell$uri$is_args$args;
       }

       # Forwarding rule api v1
       # Use the correct scheme in the proxy_pass
       location ^~ /api/v1/<<Pulsar cluster name>> {
         rewrite ^/api/v1/<<Pulsar cluster name>>/(.*)$ /admin/v2/$1 break;
         proxy_pass http://http-pulsar-proxy$uri$is_args$args;
       }

       # For use when keycloak is the authentication/identity provider
       # Use the correct scheme in the proxy_pass
       # For Okta, use /token for <<Identity Provider Token Endpoint>>. https://developer.okta.com/docs/reference/api/oidc/#token
       location ^~ /api/v1/auth/token {
         rewrite  ^.*$ <<Identity Provider Token Endpoint>> break;
         proxy_pass http://$uri$is_args$args;
       }
d
       listen 8080 default_server;

       # When using SSL/TLS, add the below block.
       listen 8443 ssl;
       ssl_certificate <</path/to/tls.crt>>;
       ssl_certificate_key <</path/to/tls.key>>;
       ssl_protocols TLSv1.2 TLSv1.3;

 }

 server {

   location = /nginx_status {
     stub_status;

     access_log off;
     allow 127.0.0.1;
     deny all;

   }

   listen 8081 ;

 }

}
----

== Next 

To install the admin console in a cloud environment, see the xref::admin-console-tutorial.adoc[Admin Console Tutorial].
