= Luna Streaming FAQs

If you're new to DataStax Luna Streaming and its Apache Pulsar enhancements, these FAQs are for you.

What is DataStax Luna Streaming?::

DataStax Luna Streaming is a new Kubernetes-based distribution of Apache Pulsar, based on the technology that https://kesque.com/[Kesque] built to run its Pulsar-as-a-service.

What components and features are provided by Luna Streaming?::

In addition to Apache Pulsar itself, Luna Streaming provides:

* An installer that can stand up a dev or production cluster on bare metal or VMs without a pre-existing Kubernetes environment
* A helm chart that can deploy and manage Pulsar on your current Kubernetes infrastructure
* Cassandra, Elastic, Kinesis, Kafka, and JDBC connectors
* A management dashboard
* A monitoring and alerting system

On which version of Pulsar is Luna Streaming based?::

Luna Streaming is based on Apache Pulsar 2.6.2 plus a number updates that are listed in https://github.com/riptano/pulsar-distro/blob/master/releases/2.6.2_ds/release-notes.txt.

Where are the Luna Streaming public GitHub repos?::  

There are several public repos, each with different purposes. See:

// * https://github.com/datastax/pulsar : This is the distro repo (a fork of apache/pulsar).  
* https://github.com/datastax/pulsar-admin-console : This is the repo for the Pulsar admin console, which allows for the configuration and monitoring of Pulsar.
* https://github.com/datastax/pulsar-heartbeat : This is a monitoring/observability tool for Pulsar that tracks the health of the cluster and can generate alerts in Slack and OpsGenie.
* https://github.com/datastax/pulsar-helm-chart : This is the Helm chart for deploying the DataStax Pulsar Distro in an existing Kubernetes cluster.
* https://github.com/datastax/pulsar-sink : This is the Pulsar Sink for Cassandra.
* https://github.com/datastax/burnell : This is a utility for Pulsar that provides various functions, such as key initialization for authentication, and JWT token creation API.

What are the install options for Luna Streaming?::

* Use the provided Helm Chart to install Luna Streaming in an existing Kubernetes cluster on your laptop or hosted by a cloud provider.
* Use the provided replicated.io packaging to install on a single or multiple server(s) or VM(s)

How do I install Luna Streaming in my Kubernetes cluster?::

We provides a Helm Chart (version 3) to add the datastax-pulsar repo and install Luna Streaming (Pulsar) on your local or cloud-provided Kubernetes cluster. Example:

----
helm repo add datastax-pulsar https://datastax.github.io/pulsar-helm-chart
curl -LOs https://datastax.github.io/pulsar-helm-chart/examples/dev-values.yaml
helm install pulsar -f dev-values.yaml datastax-pulsar/pulsar
----

You can set additional options in the values file, but the commands above represent the quick start approach. For more, see xref:quickstart-helm-installs.adoc[Quick Start for Helm Chart installs].

How do I install Luna Streaming on my server or VM?::

We provide a pre-configuration replicated.io package to install Luna Streaming on a single server/VM or multiple (4) servers/VMs. Example initial setup commands:

----
curl -sSL https://k8s.kurl.sh/datastax-distribution-pulsar | sudo bash
curl -s https://kesque-image-prod.s3.amazonaws.com/Community.yaml -o Community.yaml
bash -l
kubectl kots install datastax-distribution-pulsar --namespace default --license-file ./Community.yaml
----

Then follow the full instructions in xref:quickstart-server-installs.adoc[Quick Start for Server/VM installs].

How do I start the Luna Streaming Admin Console?::

Answer placeholder...

What task can I perform in the Luna Streaming Management Dashboard?::

Answer placeholder…

How is Luna Streaming different from DataStax Apache Kafka Connector?::

Answer placeholder...

What is Prometheus?::

Answer placeholder...

What is Grafana?::

Answer placeholder...

How do I set up an Ingress to access the metrics and Grafana?::

Answer placeholder...

Do you provide a Traefik Ingress chart?::

Answer placeholder...

What metrics are displayed by the pre-configured Grafana dashboards?::

Answer placeholder...

Which Kubernetes platforms are supported by Luna Streaming?::

Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service, Amazon Kubernetes Service (AKS), and other commonly used platforms. 

What is Pulsar Sink?::

Answer placeholder...

Is Luna Streaming an open-source project?

Yes, Luna Streaming is open source. See (github url) for information about the contribution guidelines.

What is the replicated?::

Replicated provides a container-based platform to deploy cloud-native applications inside your on-prem environment, which gives you greater security and control. Luna Streaming uses replicated to ... 
See https://www.replicated.com/. 

How do I configure the replicated.io options?::

Answer placeholder...

What client APIs does Luna Streaming provide?::

The same as for Apache Pulsar. See https://pulsar.apache.org/docs/en/client-libraries/. 

== Next

Learn now to ... ( topic link ) 
