= Luna Streaming FAQs

If you are new to DataStax Luna Streaming and its Apache Pulsar enhancements, these FAQs are for you.

== Introduction

=== What is DataStax Luna Streaming?

DataStax Luna Streaming is a new Kubernetes-based distribution of Apache Pulsar, based on the technology that https://kesque.com/[Kesque, window=_blank] built to run its Pulsar-as-a-service.

=== What components and features are provided by DataStax Luna Streaming?

In addition to Apache Pulsar itself, DataStax Luna Streaming provides:

* An installer that can stand up a dev or production cluster on bare metal or VMs without a pre-existing Kubernetes environment
* A helm chart that can deploy and manage Pulsar on your current Kubernetes infrastructure
* Cassandra, Elastic, Kinesis, Kafka, and JDBC connectors
* A management dashboard
* A monitoring and alerting system

=== On which version of Apache Pulsar is DataStax Luna Streaming based?

DataStax Luna Streaming {luna-version} is based on its distribution of Apache Pulsar {pulsar-version}, plus features and additional enhancements from DataStax contributors. 

=== What does DataStax Luna Streaming provide that I cannot get with open-source Apache Pulsar?

DataStax Luna Streaming is a hardened version of Apache Pulsar that been run through additional testing to ensure it is ready for production use. It also includes additional tooling to help monitor your system, including an enhanced Admin Console and a Heartbeat service to monitor the system health.

=== Is DataStax Luna Streaming an open-source project?

Yes, DataStax Luna Streaming is open source. See the <<gitHubRepos,repos FAQ>>. 

=== Which Kubernetes platforms are supported by DataStax Luna Streaming?

They include Minikube, K8d, Kind, Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service (AKS), Amazon Elastic Kubernetes Service (EKS), and other commonly used platforms. 

[#gitHubRepos]
=== Where are the DataStax Luna Streaming public GitHub repos?

There are several public repos, each with a different purpose. See:

* https://github.com/datastax/pulsar[https://github.com/datastax/pulsar, window=_blank] : This is the distro repo (a fork of apache/pulsar).  
* https://github.com/datastax/pulsar-admin-console[https://github.com/datastax/pulsar-admin-console, window=_blank] : This is the repo for the Pulsar admin console, which allows for the configuration and monitoring of Pulsar.
* https://github.com/datastax/pulsar-heartbeat[https://github.com/datastax/pulsar-heartbeat, window=_blank] : This is a monitoring/observability tool for Pulsar that tracks the health of the cluster and can generate alerts in Slack and OpsGenie.
* https://github.com/datastax/pulsar-helm-chart[https://github.com/datastax/pulsar-helm-chart, window=_blank] : This is the Helm chart for deploying the DataStax Pulsar Distro in an existing Kubernetes cluster.
* https://github.com/datastax/pulsar-sink[https://github.com/datastax/pulsar-sink, window=_blank] : This is the DataStax Apache Pulsar Connector (`pulsar-sink` for Cassandra) repo.
* https://github.com/datastax/burnell[https://github.com/datastax/burnell, window=_blank] : This is a utility for Pulsar that provides various functions, such as key initialization for authentication, and JWT token creation API.

== Installation

=== Is there a prerequisite version of Java needed for the DataStax Luna Streaming installation?

The DataStax Luna Streaming distribution is designed for Java 11. However, because the product releases Docker images, you do not need to install Java (8 or 11) in advance. Java 11 is bundled in the Docker image.

=== What are the install options for DataStax Luna Streaming?

* Use the provided Helm Chart to install DataStax Luna Streaming in an existing Kubernetes cluster on your laptop or hosted by a cloud provider.
* Use the tarball provided at https://pulsar.apache.org/docs/en/standalone/

=== How do I install DataStax Luna Streaming in my Kubernetes cluster?

Follow the full instructions in xref:quickstart-helm-installs.adoc[Quick Start for Helm Chart installs].

=== How do I install DataStax Luna Streaming on my server or VM?

Follow the full instructions in xref:quickstart-server-installs.adoc[Quick Start for Server/VM installs].

