= Georeplication

You must enable geo-replication on a per-tenant basis in Pulsar. You can enable geo-replication between clusters only when a tenant is created that allows access to both clusters.

Although geo-replication must be enabled between two clusters, actually geo-replication is managed at the namespace level. You must complete the following tasks to enable geo-replication for a namespace:

* Enable geo-replication namespaces
* Configure that namespace to replicate across two or more provisioned clusters

Any message published on any topic in that namespace is replicated to all clusters in the specified set.

== Configuring georeplication

The following example connects three clusters: *us-east*, *us-west*, and *us-cent*.

To replicate data among clusters, you need to configure each cluster to connect to the other. You can use the pulsar-admin tool to create a connection.

Suppose that you have 3 replication clusters: `us-west`, `us-cent`, and `us-east`.

Configure the connection from `us-west` to `us-east`.

Run the following command on `us-west`.

----
$ bin/pulsar-admin clusters create \
  --broker-url pulsar://<DNS-OF-US-EAST>:<PORT> \
  --url http://<DNS-OF-US-EAST>:<PORT> \
  us-east
----

. Configure the connection from `us-west` to `us-cent`.

Run the following command on `us-west`:

----
$ bin/pulsar-admin clusters create \
  --broker-url pulsar://<DNS-OF-US-CENT>:<PORT> \
  --url http://<DNS-OF-US-CENT>:<PORT> \
  us-cent
----

. Run similar commands on `us-east` and `us-cent` to create connections among clusters.

== Enable georeplication at namespace level

----
$ bin/pulsar-admin namespaces create my-tenant/my-namespace
----

Once you create a geo-replication namespace, any topics that producers or consumers create within that namespace is replicated across clusters. Typically, each application uses the `serviceUrl` for the local cluster.

== Enable georeplication at topic level

----
$ bin/pulsar-admin topics set-replication-clusters --clusters us-west,us-east,us-cent my-tenant/my-namespace/my-topic
----



