= Heartbeat on VM/Server

:page-tag: luna-streaming,dev,admin,pulsar

This document describes how to install Pulsar Heartbeat on a virtual machine (VM) or server. For installation with the Docker image, see xref:quickstart-helm-installs.adoc[Helm Chart Installation].

== Install Heartbeat Binary

. Use the Linux commands `uname -m` and `uname -o` to determine your process architecture.
+
For example, `uname -m` in Ubuntu might return `x86_64`, and `uname -o` returns `GNU/Linux`.

. Download the heartbeat binary `.gz` file matching your OS and process architecture from the https://github.com/datastax/pulsar-heartbeat/releases[releases page].

. Uncompress the file to be an executable binary. The filename structure is `pulsar-heartbeat-{version}-{os}-{arch}`. 

Here is an example using Gunzip:
[subs=attributes+]
----
$ gunzip ~/Downloads/pulsar-heartbeat-{heartbeat-version}-linux-amd64 
$ ls ~/Downloads/pulsar-heartbeat-{heartbeat-version}-linux-amd64
/Users/username/Downloads/pulsar-heartbeat-{heartbeat-version}-linux-amd64
----

== Execute Heartbeat binary

The Pulsar Heartbeat configuration is defined by a `.yaml` file. A yaml template for Heartbeat is available at https://github.com/datastax/pulsar-heartbeat/blob/master/config/runtime-template.yml[]. In this file, the environmental variable `PULSAR_OPS_MONITOR_CFG` tells the application where to source the file. 

Run the binary file `pulsar-heartbeat-{version}-{os}-{arch}`.

Here is an example of how to set up and run the application:

[subs=attributes+]
----
$ export PULSAR_OPS_MONITOR_CFG=/Users/username/go/src/github.com/datastax/pulsar-heartbeat/config/runtime.yml 

$ ./pulsar-heartbeat-{heartbeat-version}-linux-amd64 
2022/01/11 15:16:57  info config file /Users/username/go/src/github.com/datastax/pulsar-heartbeat/config/runtime.yml
----

== Next

Learn more about monitoring your cluster with Heartbeat xref:pulsar-monitor.adoc[here].

