= Heartbeat on VM/Server

This document describes how to install Pulsar Heartbeat on a virtual machine (VM) or server. For installation with the Docker image, see xref:quickstart-helm-installs.adoc[Helm Chart Installation].

== Install Heartbeat Binary

The release page is at https://github.com/datastax/pulsar-heartbeat/releases. The latest version is 1.0.12, which matches with the Git release tag and Docker image.

Download the binary `.gz` file matching your OS and process architecture. Use the Linux commands `uname -m` and `uname -o` to determine your process architecture.

For example, if I run the command `uname -m` in Ubuntu, my system returns `x86_64`, and `uname -o` returns `GNU/Linux`. The link to download the matching binary would be https://github.com/datastax/pulsar-heartbeat/releases/download/1.0.12/pulsar-heartbeat-1.0.12-linux-amd64.gz from the release page.

Once the file is downloaded, uncompress the file with Gunzip. It will become a binary that can be executed. The filename structure is `pulsar-heartbeat-{version}-{os}-{arch}`. 

Here is an example:

----
$ gunzip ~/Downloads/pulsar-heartbeat-1.0.12-linux-amd64 
$ ls ~/Downloads/pulsar-heartbeat-1.0.12-linux-amd64
/Users/username/Downloads/pulsar-heartbeat-1.0.12-linux-amd64
----

== Execute Heartbeat binary

The Pulsar Heartbeat configuration is defined by a `.yaml` file. A yaml template for Heartbeat is available at https://github.com/datastax/pulsar-heartbeat/blob/master/config/runtime-template.yml[].

The environmental variable `PULSAR_OPS_MONITOR_CFG` tells the application where to source the file. 

Run the binary file `pulsar-heartbeat-{version}-{os}-{arch}`. Here is an example of how to set up and run the application:

----
$ export PULSAR_OPS_MONITOR_CFG=/Users/{username}/go/src/github.com/datastax/pulsar-heartbeat/config/runtime.yml 

$ ./pulsar-heartbeat-1.0.12-linux-amd64 
2022/01/11 15:16:57  info config file /Users/{username}/go/src/github.com/datastax/pulsar-heartbeat/config/runtime.yml
----

== Next

To install Heartbeat packaged with the Luna Streaming Helm chart, see xref:quickstart-helm-installs.adoc[Helm Chart Installation].

