= Luna Streaming Installation on Google Kubernetes Environment

This document will cover installation of Luna Streaming on the Google Kubernetes Environment (GKE). 

For an example set of production cluster values, see the DataStax production-ready https://github.com/datastax/pulsar-helm-chart[Helm chart]. +

DataStax recommends these hardware resources for running Luna Streaming in a Kubernetes environment: +

include::partial$helm-chart-recommendations.adoc[]

For the local machine running the Helm chart, you will need: +

* https://helm.sh/docs/[Helm] version 3 +
* A Google account with privileges to install and configure Kubernetes resources. 

== Helm chart `values.yaml`

The https://github.com/datastax/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/values.yaml[`values.yaml`] will deploy Pulsar with:

* 1 ZooKeeper cluster with `replicaCount:3`
* 1 Bookkeeper cluster with `replicaCount:3`
* 1 Broker cluster with `replicaCount: 3`
** Ledgers: `defaultEnsembleSize: 2`, `defaultAckQuorum: 2`, `defaultWriteQuorum: 2`
* 1 Function cluster with a `replicaCount: 2`

=== `default_storage`
The `default_storage` parameter in `values.yaml` controls the default storage class for all persistent volumes created by the Helm chart.

[source,yaml]
----
default_storage:
  existingStorageClassName: default
----

For a component like BookKeeper, which requires stateful storage, we need to override the `default_storage` class when the BookKeeper Persistent Volume Claims (PVCs) are created.

There are two ways to override `default_storage`:

* Leave `existingStorageClassName` blank and specify the storage class parameters below.
+
[source,yaml]
----
  volumes:
    journal:
      name: journal
      size: 20Gi
        existingStorageClassName: 
        storageClass:
         provisioner: kubernetes.io/gce-pd
         type: pd-ssd
         fsType: ext4
         extraParams:
            replication-type: none
----

* Create a custom storage configuration as a `yaml` file (https://github.com/datastax/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/templates/bookkeeper/bookkeeper-storageclass.yaml[like the DataStax example]) and tell the Helm chart to use that storage configuration when it creates the BookKeeper PVCs.
+
[source,yaml]
----
  volumes:
    journal:
      name: journal
      size: 20Gi
        existingStorageClassName: bookkeeper-storageclass.yaml
----

=== GKE-specific storage class 

Here is an example `storage-values.yaml` as used above for the BookKeeper node. Paste it into a `yaml` file to provision a persistent SSD with the `ext4` file system.

[source,yaml]
----
storage_class:
    provisioner: kubernetes.io/gce-pd
    type: pd-ssd
    fsType: ext4
    extraParams:
        replication-type: none
----

== Install Luna Streaming to GKE

Once you have added your storage settings to the `storage-values.yaml` file, install the Helm chart. 

. Create the namespace; in this example, we use `pulsar`.
+
----
kubectl create namespace pulsar
----

. Run this Helm command using the `storage-values.yaml` provisioning:
+
----
helm install pulsar datastax-pulsar/pulsar --namespace pulsar --values storage_values.yaml --create-namespace
----

. To avoid having to specify the `pulsar` namespace on each subsequent command, set the namespace context. Example:
+
----
kubectl config set-context $(kubectl config current-context) --namespace=pulsar
----

. Execute `kubectl get pods -A` to view your running pods. 

== What's next?
Once your pods are up and running, continue to xref:install-upgrade:quickstart-helm-installs.adoc#manage-pulsar-cluster[Accessing Pulsar Cluster in Cloud] to access and manage your cluster.

* To learn more about using the Pulsar Admin Console, see xref:components:admin-console-tutorial.adoc[Admin Console Tutorial].
* To learn more about installing Pulsar on a server or virtual machine, see xref:install-upgrade:quickstart-server-installs.adoc[Quickstart for Server/VM Install].