= Luna Streaming IO Connectors

When you have Luna Streaming installed and running, add IO connectors to your deployment to interact with external systems, such as Apache Cassandra, Elastic Search, and many others.

== Source Connectors

Source connectors pull messages _from_ external topics and persist the messages _to_ Pulsar topics.

Explore source connector configurations and code examples https://pulsar.apache.org/docs/en/io-connectors/#source-connector[here].

== Sink Connectors

Sink connectors are used to pull messages _from_ Pulsar topics and persist the messages _to_ external systems.

Explore sink connector configurations and code examples https://pulsar.apache.org/docs/en/io-connectors/#sink-connector[here].

== Processing Guarantees

Processing guarantees are used to handle errors when writing messages to Pulsar topics.

* *ATLEAST_ONCE*: Each message sent to the source can be processed more than once.
* *ATMOST_ONCE*: The message sent to the source is processed at most once. Therefore, there is a chance that the message is not processed.
* *EFFECTIVELY_ONCE*: Each message sent to the source will have one output associated with it.

Learn more about processing guarantees https://pulsar.apache.org/docs/en/io-overview/#processing-guaranteehere].
== Next

Learn more about Pulsar IO connectors https://pulsar.apache.org/docs/en/io-overview/[here].




