= Pulsar Monitor

Pulsar Monitor monitors the availability, tracks the performance, and reports failures of the Pulsar cluster.
It produces synthetic workloads to measure end-to-end message pubsub latency.

It is a cloud native application that can be installed by Helm within the Pulsar Kubernetes cluster.

Here is a list of features that Pulsar Monitor supports.

* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++monitor Pulsar admin REST API endpoint
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++measure end-to-end message latency from producing to consuming messages
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++for latency measure, it can produce a list of messages with user specified payload size and the number of messages
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++measure average latency over a list of messages
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++detect out of order delivery of a list of generated messages
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++measure a single message latency over the websocket interface
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++measure message latency generated by Pulsar function
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++monitor instance availability of broker, proxy, bookkeeper, and zookeeper in a Pulsar Kubernetes cluster
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++monitor individual Pulsar broker's health
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled">++++++</input>+++Pulsar function trigger over HTTP interface
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++incident alert with OpsGenie with automatic alert clear and deduplication
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++customer configurable alert threshold and probe test interval
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++tracking analytics and usage
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++dead man's snitch heartbeat monitor with OpsGenie
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++alert on Slack
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++monitor multiple Pulsar clusters (with no kubernetes pods monitoring)
* +++<input type="checkbox" class="task-list-item-checkbox" disabled="disabled" checked="checked">++++++</input>+++co-resident monitoring within the same Pulsar Kubernetes cluster

This is a data driven tool that sources configuration from a yaml or json file.
Here is a link:../config/runtime_template.json[template].
The configuration json file can be specified in the overwrite order of

* an environment variable `PULSAR_OPS_MONITOR_CFG`
* an command line argument `./pulsar-monitor -config /path/to/pulsar_ops_monitor_config.yml`
* A default path to `../config/runtime.yml`

== Observability

This tool exposes Prometheus compliant metrics at `\metrics` endpoint for scraping.
The exported metrics are:

[cols="<,^,<"]
|===
| Name | Type | Description

| pulsar_pubsub_latency_ms
| gauge
| end to end message pub and sub latency in milliseconds

| pulsar_pubsub_latency_ms_hst
| summary
| end to end message latency histogram summary over 50%, 90%, and 99% samples

| pulsar_websocket_latency_ms
| gauge
| end to end message pub and sub latency over websocket interface in milliseconds

| pulsar_k8s_bookkeeper_offline_counter
| gauge
| bookkeeper offline instances in Kubernetes cluster

| pulsar_k8s_broker_offline_counter
| gauge
| broker offline instances in the Kubernetes cluster

| pulsar_k8s_proxy_offline_counter
| gauge
| proxy offline instances in the Kubernetes cluster

| pulsar_k8s_bookkeeper_zookeeper_counter
| gauge
| zookeeper offline instances in the Kubernetes cluster

| pulsar_monitor_counter
| counter
| pulsar monitor heartbeat counter

| pulsar_tenant_size
| gauge
| the number of tenants that can be used as a health indicator of admin interface
|===

== In-cluster monitoring

Pulsar monitor can be deployed within the same Pulsar Kubernetes cluster.
Kubernetes' pod and service , and individual broker monitoring are only supported within the same Kubernetes cluster deployment.

== Docker

Pulsar Monitor's official docker image can be pulled https://hub.docker.com/repository/docker/kesque/pulsar-monitor[here]

=== Docker compose

`./config/runtime.yml` or `./config/runtime.json` must have a Pulsar jwt and configured properly.

[source,bash]
----
$ docker-compose up
----

=== Docker example

The runtime.yml/yaml or runtime.json file must be mounted to /config/runtime.yml as the default configuration path.

This command runs a multi stage build to produce a docker image.

 $ make

Run docker container with Pulsar CA certificate and expose Prometheus metrics for collection.

[source,bash]
----
$ docker run -d -it -v $HOME/go/src/github.com/kafkaesque-io/pulsar-monitor/config/runtime.yml:/config/runtime.yml -v /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/ssl/certs/ca-bundle.crt -p 8080:8080 --name=pulsar-monitor kesque/pulsar-monitor:1.2.91
----

== Helm chart

=== Install as an individual deployment using helm

Pulsar Monitor can be installed by this https://github.com/kafkaesque-io/pulsar-helm-chart/tree/master/helm-chart-sources/pulsar-monitor[helm chart] With this chart, it can monitor mutliple remote Pulsar clusters or co-reside on the same Pulsar cluster. Use helm version 3.

----
helm install pulsar-monitor kafkaesque/pulsar --namespace monitoring --values ./config/helm-values/pulsar-monitor-values.yaml
----

=== Install as part of Kesque Pulsar cluster using helm

Pulsar Monitor can be directly enabled inside https://github.com/kafkaesque-io/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/values.yaml#L1571[the Kesque's Pulsar chart]

== Development

=== How to build

This script builds the Pulsar Monitor Go application, runs code static analysis(golint), runs unit tests, and creates a binary under ./bin/pulsar-monitor.

 $ ./scripts/ci.sh
