= Pulsar Heartbeat

Pulsar Heartbeat monitors the availability, tracks the performance, and reports failures of the Pulsar cluster.
It produces synthetic workloads to measure end-to-end message pubsub latency.

Pulsar Heartbeat is a cloud native application that can be installed by Helm within a Pulsar Kubernetes cluster.

TIP: Pulsar Heartbeat is installed automatically for server/VM installations as described in xref::quickstart-server-installs.adoc[].

Pulsar Heartbeat supports the following features:

* Monitor Pulsar admin REST API endpoint
* Measure end-to-end message latency from producing to consuming messages
* Produce a list of messages with user specified payload size and the number of messages for latency measurements
* Measure average latency over a list of messages
* Detect out of order delivery of a list of generated messages
* Measure a single message latency over the websocket interface
* Measure message latency generated by Pulsar function
* Monitor instance availability of broker, proxy, bookkeeper, and zookeeper in a Pulsar Kubernetes cluster
* Monitor individual Pulsar broker's health
* Trigger Pulsar functions over an HTTP interface
* Incident alerts with OpsGenie with automatic alert clear and deduplication
* Customer configurable alert thresholds and probe test intervals
* Tracking analytics and usage
* Dead man's snitch heartbeat monitor with OpsGenie
* Slack alerts
* Multiple Pulsar cluster monitoring (with no Kubernetes pods monitoring)
* Co-resident monitoring within the same Pulsar Kubernetes cluster

== Configuration

Pulsar Heartbeat is a data driven tool that sources configuration from a yaml or json file. The configuration json file can be specified in the following order of precedence:

* An environment variable `PULSAR_OPS_MONITOR_CFG`
* A command line argument `./pulsar-monitor -config /path/to/pulsar_ops_monitor_config.yml`
* A default path to `../config/runtime.yml`

You can download a template https://github.com/datastax/pulsar-heartbeat/blob/master/config/runtime-template.json[here].

== Observability

Pulsar Heartbeat exposes Prometheus compliant metrics at the `\metrics` endpoint for scraping. The exported metrics are:

[cols="<,^,<"]
|===
| Name | Type | Description

| pulsar_pubsub_latency_ms
| gauge
| end to end message pub and sub latency in milliseconds

| pulsar_pubsub_latency_ms_hst
| summary
| end to end message latency histogram summary over 50%, 90%, and 99% samples

| pulsar_websocket_latency_ms
| gauge
| end to end message pub and sub latency over websocket interface in milliseconds

| pulsar_k8s_bookkeeper_offline_counter
| gauge
| bookkeeper offline instances in Kubernetes cluster

| pulsar_k8s_broker_offline_counter
| gauge
| broker offline instances in the Kubernetes cluster

| pulsar_k8s_proxy_offline_counter
| gauge
| proxy offline instances in the Kubernetes cluster

| pulsar_k8s_bookkeeper_zookeeper_counter
| gauge
| zookeeper offline instances in the Kubernetes cluster

| pulsar_monitor_counter
| counter
| pulsar monitor heartbeat counter

| pulsar_tenant_size
| gauge
| the number of tenants that can be used as a health indicator of admin interface
|===

== In-cluster monitoring

Pulsar Heartbeat can be deployed within the same Pulsar Kubernetes cluster.

NOTE: Kubernetes' pod and service, and individual broker monitoring are only supported within the same Kubernetes cluster deployment.

== Docker

Pulsar Monitor's official docker image can be pulled https://hub.docker.com/repository/docker/kesque/pulsar-monitor[here]

=== Docker compose

`./config/runtime.yml` or `./config/runtime.json` must have a Pulsar jwt and must be configured properly.

[source,bash]
----
$ docker-compose up
----

=== Docker example

The runtime.yml/yaml or runtime.json file must be mounted to /config/runtime.yml as the default configuration path.

This command runs a multi stage build to produce a docker image.

[source,bash]
----
$ make
----

Run docker container with Pulsar CA certificate and expose Prometheus metrics for collection.

[source,bash]
----
$ docker run -d -it -v $HOME/go/src/github.com/kafkaesque-io/pulsar-monitor/config/runtime.yml:/config/runtime.yml -v /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/ssl/certs/ca-bundle.crt -p 8080:8080 --name=pulsar-monitor kesque/pulsar-monitor:1.2.91
----

== Helm chart

=== Install as an individual deployment using helm

Pulsar Heartbeat can be installed by this https://github.com/kafkaesque-io/pulsar-helm-chart/tree/master/helm-chart-sources/pulsar-monitor[helm chart] (Helm version 3) With that chart, it can monitor multiple remote Pulsar clusters or co-reside on the same Pulsar cluster.

[source,bash]
----
helm install pulsar-monitor kafkaesque/pulsar --namespace monitoring --values ./config/helm-values/pulsar-monitor-values.yaml
----

== Development

=== How to build

This script builds the Pulsar Heartbeat Go application, runs code static analysis (golint), runs unit tests, and creates a binary under ./bin/pulsar-monitor:

[source,bash]
----
$ ./scripts/ci.sh
----