= Quick Start for Server/VM installs

You have two options for installing DataStax Luna Streaming (Pulsar):

* Via the provided Helm chart for an existing Kubernetes environment on a laptop or with a cloud provider. See xref:quickstart-helm-installs.adoc[Quick Start for Helm Chart installs]. 
* Via replicated.io packaging for deployment to a single server/VM, or to multiple servers/VMs, as covered in this topic.

Luna Streaming takes care of the replicated.io packaging details and deployment for you. The resulting deployment includes:

* Apache Pulsar
* Management Dashboard
* Prometheus/Grafana/Alertmanager
* Ready-made Grafana dashboards and Alertmanager rules
* Support for TLS and token-based authentication

== Requirements

* For a single node install, a server with at least 8 CPU and 32 GB of memory is required
* For a small HA, 4 servers are required
* The server should have at least a 40 GB drive. However, the size depends on how much data you want to be able to store. If you want to be able to store 500 GB of message data, then you need a 540 GB drive.

== Installation steps

. Install the base system.
+
----
curl -sSL https://k8s.kurl.sh/datastax-distribution-pulsar-unstable | sudo bash
----
+
This will take about 10 minutes to complete.
Near the conclusion of the command output, note the URL for connecting to the admin interface and the password.
For example:
+
----
. . . 
		Installation
		  Complete ✔

Kotsadm: http://10.101.37.2:8800
Login with password (will not be shown again): Wm501W6GY
----
+
. Install the community license.
+
----
curl -s https://kesque-image-prod.s3.amazonaws.com/Community_Beta.yaml -o Community_Beta.yaml
bash -l
kubectl kots install datastax-distribution-pulsar --namespace default --license-file ./Community_Beta.yaml
----
TIP: If necessary on your node, preface the `kubectl` command above with `sudo kubectl`
+
. Open the admin interface URL in a browser. In the example command output above, it's http://10.101.37.2:8800. 
. Add the TLS hostname and certificate information.
  If you don't enter TLS information, a self-signed certificate will be used.
. Login to the adminstration application.
+
The user name is `admin`.
The password was displayed after installing the base system.
+
. Select the configuration options: single-node vs small HA, TLS enabled (for Pulsar clients), Authentication enabled (for Pulsar admin and clients)
. Let the pre-flight checks complete, then deploy the application.
. Once the application is deployed and the status is green, connect to the dashboard using https://<ip-or-hostname>/.
You can connect directly to the Grafana interface using https://<ip-or-hostname>/.
+
The username is 'admin'.
The password is 'Z562xRxS9HYRHf'.
In the future, this will be randomly generated on install.
. Work with your new Pulsar cluster. You can view/create topics, namespaces, tenants, functions, sinks, and source. You can connect a test client (Test Clients) directly from the admin console and you can view the built-in Grafana dashboards (Cluster/Monitoring).

