= Scaling your Luna Streaming cluster

== Setting up `minikube`

. Set up a `minikube`.
+
[source,shell]
----
$ minikube start --disk-size 50000mb
----

. Connect to the load balancer with `tunnel`.
+
[source,shell]
----
$ minikube tunnel
----

== Install

For our installation, use this https://github.com/datastax/pulsar-helm-chart[Helm chart]. 

To start the cluster, use this https://github.com/datastax/pulsar-helm-chart/blob/master/examples/dev-values.yaml[YAML file].

----
$ diff ~/dev-values.yaml ~/dev-values_large.yaml 
40c40,47
<   replicaCount: 1
---
>   replicaCount: 4
>   volumes:
>     journal:
>       size: 2Gi
>     ledgers:
>       size: 10Gi
>     ranges:
>       size: 1Gi
52,54c59,61
<     defaultEnsembleSize: 1
<     defaultAckQuorum: 1
<     defaultWriteQuorum: 1
---
>     defaultEnsembleSize: 3
>     defaultAckQuorum: 2
>     defaultWriteQuorum: 3
----

. Create the cluster by installing Pulsar with `dev-values_large.yaml`:
+
----
$ helm install pulsar -f ~/dev-values_large.yaml --wait datastax-pulsar/pulsar
----

== Generating data

. Generate data in our namespaces:
+
----
$ bin/pulsar-admin namespaces set-retention public/default -t -1 -s 100M
$ bin/pulsar-client produce test1 -n 500 -m "sdasdsdsadsadsad"
$ bin/pulsar-client produce test2 -n 500 -m "sdasdsdsadsadsad"
$ bin/pulsar-client produce test3 -n 500 -m "sdasdsdsadsadsad"
----

. Ensure all bookies have some ledgers assigned to them:
+
----
$ ./bin/bookkeeper shell listledgers -meta | grep pulsar-bookkeeper-3
----

== Destroying Persistent Volume Claim (PVC)

To downscale a bookie and destroy its persistent volume claim (PVC):

----
 bookkeeper:
    replicaCount: 3

$ helm upgrade pulsar -f ~/dev-values_large.yaml --wait datastax-pulsar/pulsar
----

== Delete PVC

To delete the PVC:
----
$ kubectl delete pvc pulsar-bookkeeper-ledgers-pulsar-bookkeeper-3
----

== Scaling back your cluster

To scale back your cluster:

[source,shell]
----
 bookkeeper:
    replicaCount: 4

$ helm upgrade pulsar -f ~/dev-values_large.yaml --wait datastax-pulsar/pulsar
----

Now, bookkeeper-3 will fail to start with
`org.apache.bookkeeper.bookie.BookieException$InvalidCookieException`.

== Recovering from lost PVC

. Track under-replicated ledgers from any live bookie:
+
[source,shell]
----
$ ./bin/bookkeeper shell listunderreplicated
----

. Double-check bookie id of the failing bookie:
+
[source,shell]
----
$ ./bin/bookkeeper shell listbookies -a
----
+
This command returns `Cannot resolve pulsar-bookkeeper-3.pulsar-bookkeeper.default.svc.cluster.local:3181, bookie is unknown`.

[start=3]
. Decommission the bookie:
+
[source,shell]
----
$ ./bin/bookkeeper shell decommissionbookie -bookieid pulsar-bookkeeper-3.pulsar-bookkeeper.default.svc.cluster.local:3181
----
+
The cookie of the decommissioned bookie: `pulsar-bookkeeper-3.pulsar-bookkeeper.default.svc.cluster.local:3181` is deleted.

. Restart failing bookie with Ctrl-K in k8s or wait for k8s to restart it again.
+
The bookie should restart and rejoin the cluster. As expected with deleted PVC, data is lost.

== Better scale down procedure

. Ensure there are no under-replicated ledgers.
. Downscale the cluster.
+ 
New under replicated ledgers will appear.
. Decommission the removed bookie.
+
[NOTE]
====
The decommissioning will take some time because it triggers the audit and auto-recovery and blocks until auto-recovery completes. 
====
+
[NOTE]
====
There is an option to scale back if something fails.
====

. Delete the ledger and journal PVCs of decommissioned bookie.




