= Luna Streaming Tools and UIs

This page describes tools and UI for Datastax Luna Streaming. 

== How do I start the DataStax Luna Streaming Admin Console?

See the following topics:

* If you installed Luna Streaming via the Helm Chart for a Kubernetes environment residing on your laptop or with a cloud provider, see xref:quickstart-helm-installs.adoc[Quick Start for Helm Chart installs].  
* If you installed Luna Streaming via the tarball package on a large server/VM or in a small HA (4 node cluster), see xref:quickstart-server-installs.adoc[Quick Start for Server/VM installs]. 

== What task can I perform in the DataStax Luna Streaming Installation Console?

From the Installation Console, you can:

* Configure the DataStax Luna Streaming environment
* View and update the DataStax Luna Streaming version and application status
* Get the host URL and generated password to launch the DataStax Luna Streaming Admin Console
* Set up and view Grafana graphs, which display metrics collected by the provided Prometheus Operator
* Analyze DataStax Luna Streaming to collect information you could provide for Support
* Sync the license that enables DataStax Luna Streaming software
* View upstream, midstream, and downstream files used by DataStax Luna Streaming

== What task can I perform in the DataStax Luna Streaming Admin Console?

From the Admin Console, you can:

* Add and run Pulsar clients
* Establish credentials for secure connections 
* Define topics that can be published for streaming apps
* Set up Pulsar sinks that publish topics and make them available to subscribers, such as for a Cassandra database table
* Control namespaces used by Pulsar
* Use the Admin API

== What is Pulsar Heartbeat?

https://github.com/datastax/pulsar-heartbeat[Pulsar Heartbeat] monitors the availability, tracks the performance, and reports failures of the Pulsar cluster. It produces synthetic workloads to measure end-to-end message pubsub latency.  Pulsar Heartbeat is a cloud-native application that can be installed by Helm within the Pulsar Kubernetes cluster.

== What is Prometheus?

https://prometheus.io/docs/introduction/overview/[Prometheus] is an open-source tool to collect metrics on a running app, providing real-time monitoring and alerts.

== What is Grafana?

https://grafana.com/[Grafana] is a visualization tool that helps you make sense of metrics and related data coming from your apps via Prometheus, for example. 

== Pulsar Connector

=== What are the features provided by DataStax Apache Pulsar Connector (`pulsar-sink`) that are not supported in `kafka-sink`?

* Single record acknowledgement and negative acknowledgements.
* The https://pulsar.apache.org/docs/en/io-overview/[Pulsar IO framework] provides many features that are not possible in Kafka, and has different compression formats and auth/security features. The features are handled by Pulsar.

=== What features are missing in DataStax Apache Pulsar Connector (`pulsar-sink`) compared with `kafka-sink`?

* No support for `tinyint` (`int8bit`) and `smallint` (`int16bit`).
* The key is always a String, but you can write JSON inside it; the support is implemented in pulsar-sink, but not in Pulsar IO.
* The “value” of a “message property” is always a String; for example, you cannot map the message property to `__ttl` or to `__timestamp`.
* Field names inside structures must be valid for Avro, even in case of JSON structures. For example, field names like `Int.field` (with dot) or `int field` (with space) are not valid.

=== How is DataStax Apache Pulsar Connector distributed?

There are two packages:

* The `pulsar-sink` functionality of DataStax Apache Pulsar Connector is included with DataStax Luna Streaming. It's built in!
* You can optionally download the DataStax Apache Pulsar Connector tarball from the https://downloads.datastax.com/#pulsar-sink[DataStax Downloads] site, and then use it as its own product with your open-source Apache Pulsar install. 

If you're using open-source software (OSS) Apache Pulsar, you can use DataStax Apache Pulsar Connector with the OSS to take advantage of this `pulsar-sink` for Cassandra. See the DataStax Apache Pulsar Connector https://docs.datastax.com/en/pulsar-connector/[documentation].

== APIs

=== What client APIs does DataStax Luna Streaming provide?

The same as for Apache Pulsar. See https://pulsar.apache.org/docs/en/client-libraries/. 

== Next

Learn how to install DataStax Luna Streaming via the xref:quickstart-helm-installs.adoc[Helm Chart] or for the xref:quickstart-server-installs.adoc[Server/VM Installs].
