= Pulsar Beam with Luna Streaming
:navtitle: Pulsar Beam with Luna Streaming
:description: Install a minimal Luna Streaming helm chart that includes Pulsar Beam
:title: Pulsar Beam with Luna Streaming
:helmValuesPath: https://raw.githubusercontent.com/datastaxdevs/luna-streaming-examples/main/beam/values.yaml

The https://github.com/kafkaesque-io/pulsar-beam[Pulsar Beam^]{external-link-icon} project is an HTTP-based streaming and queueing system for use with Apache Pulsar.

With Pulsar Beam, you can send messages over HTTP, push messages to a webhook or cloud function, chain webhooks and functions together, or stream messages via https://www.html5rocks.com/en/tutorials/eventsource/basics/[server-sent events^]{external-link-icon}.

In this guide we will install a minimal DataStax Pulsar Helm chart that includes Pulsar Beam.

== Prerequisites

You will need the following things in place to complete this guide:

* https://helm.sh/docs/intro/install/[Helm 3 CLI^]{external-link-icon} (this example uses version 3.8.0)
* Enough access to a K8s cluster to create a namespace, deployments, and pods
* https://kubernetes.io/docs/tasks/tools/[Kubectl CLI^]{external-link-icon} (this example uses version 1.23.4)

== Install Luna Streaming helm chart

include::partial$install-helm.adoc[]

== Forward service port

include::partial$port-forward-beam.adoc[]

== Start a message consumer

In a new terminal window, run the following curl command to begin streaming server sent events.
See xref:astra-streaming:developing:configure-pulsar-env.adoc[configuring your local environment for Astra Streaming^].
[source,shell]
----
TOPIC="my-beam-topic"
curl http://127.0.0.1:8085/v2/sse/persistent/public/default/$TOPIC?SubscriptionInitialPosition=earliest&SubscriptionType=exclusive&SubscriptionName=my-beam-subscription
----

== Produce a new message

Going back to the original terminal window, run the following script to produce a new message. Don't worry about creating the topic, if it doesn't exist the topic will be created automatically.

[source,shell]
----
TOPIC="my-beam-topic"
curl --request POST \
  -d "Hi there" \
  http://127.0.0.1:8085/v2/firehose/persistent/public/default/$TOPIC
----

== Consume the message

The message consumer should output the data of the new message just produced.

----
id: {9 0 0 0 <nil> 0xc002287ad0}
data: Hi there
----

TIP: Note the use of `SubscriptionInitialPosition=earliest` when your started the message consumer. This instructs Beam to create a subscription on the topic, starting at the earliest message. Try changing the value to `latest` to only receive new messages that arrive.

You have gone through the basics of using Beam in a Pulsar Cluster. Refer to the project's readme to see all the possibilities.

== A python producer & consumer

This is another example of producing and consuming messages using Beam. Unlike the above example that used curl, this example uses the "requests" python library to issue HTTP requests.

First create a new file to hold the python code.

[source,shell]
----
touch beam.py
----

Paste the following code in the new file.

[source,python]
----
include::{luna-streaming-examples-repo}/beam/produce-consume.py[]
----

Run the python example (we used version 3.8.10).

[source,shell]
----
python3 beam.py
----

The output should show 1 message was published and 1 message was consumed.

----
Published 1 message (200)
Consumed messages (200):
{
  "limit": 10,
  "size": 1,
  "messages": [
    {
      "payload": "SGkgdGhlcmUh",
      "topic": "persistent://public/default/my-beam-topic",
      "eventTime": "2023-01-03T15:52:24.054Z",
      "publishTime": "2023-01-03T15:52:24.054Z",
      "messageId": "&{ledgerID:16 entryID:0 batchIdx:0 partitionIdx:0 tracker:<nil> consumer:0xc002287e10}",
      "key": ""
    }
  ]
}
----

NOTE: The payload is base64 encoded. Simply decode the string to see the actual message data.

== Clean up

Go to each window running an open process and `ctrl-c`. That will end the process. To completely remove all traces of the chart remove the namespace.

[source,shell]
----
kubectl delete namespace datastax-pulsar
----

If you want to keep the data, just uninstall the chart.

[source,shell]
----
helm --namespace datastax-pulsar uninstall my-pulsar-cluster
----

== Next steps

Here are links to resources and guides you might be interested in:

* https://github.com/kafkaesque-io/pulsar-beam[Learn more^]{external-link-icon} about the Pulsar Beam project
* The swagger https://kafkaesque-io.github.io/pulsar-beam-swagger[Pulsar Beam API^]{external-link-icon}
* xref:pulsar-sql.adoc[]