= Pulsar Beam with Luna Streaming
:navtitle: Pulsar Beam with Luna Streaming
:description: Install a minimal Luna Streaming helm chart that includes Pulsar Beam
:helmValuesPath: https://raw.githubusercontent.com/datastaxdevs/luna-streaming-examples/main/beam/values.yaml

The https://github.com/kafkaesque-io/pulsar-beam[Pulsar Beam] project is an HTTP-based streaming and queueing system for use with Apache Pulsar.

With Pulsar Beam, you can send messages over HTTP, push messages to a webhook or cloud function, chain webhooks and functions together, or stream messages via https://www.html5rocks.com/en/tutorials/eventsource/basics/[server-sent events].

In this guide we will install a minimal DataStax Pulsar Helm chart that includes Pulsar Beam.

== Prerequisites

You will need the following prerequisites in place to complete this guide:

* https://helm.sh/docs/intro/install/[Helm 3 CLI] (this example uses version 3.8.0)
* Enough access to a K8s cluster to create a namespace, deployments, and pods
* https://kubernetes.io/docs/tasks/tools/[Kubectl CLI] (this example uses version 1.23.4)

== Install Luna Streaming Helm chart

include::partial$install-helm.adoc[]

== Forward service port

include::partial$port-forward-beam.adoc[]

== Start a message consumer

In a new terminal window, run the following curl command to begin streaming server-sent events.
See xref:astra-streaming:developing:configure-pulsar-env.adoc[configuring your local environment for Astra Streaming].

[source,shell]
----
TOPIC="my-beam-topic"
curl http://127.0.0.1:8085/v2/sse/persistent/public/default/$TOPIC?SubscriptionInitialPosition=earliest&SubscriptionType=exclusive&SubscriptionName=my-beam-subscription
----

Note the use of `SubscriptionInitialPosition=earliest` in the message consumer.
This instructs Beam to create a subscription on the topic starting at the earliest message.
Try changing the value to `latest` to only receive new messages that arrive.

== Produce a new message

Return to the original terminal window and run the following script to produce a new message.
Don't worry about creating the new topic - if a topic doesn't exist, it is created automatically.
[source,shell]
----
TOPIC="my-beam-topic"
curl --request POST \
  -d "Hi there" \
  http://127.0.0.1:8085/v2/firehose/persistent/public/default/$TOPIC
----

== Consume the message

The message consumer will output the data of the new message just produced.
[source,shell]
----
id: {9 0 0 0 <nil> 0xc002287ad0}
data: Hi there
----

You have now completed the basics of using Beam in a Pulsar Cluster. Refer to the project's https://github.com/kafkaesque-io/pulsar-beam/blob/master/README.md[readme] to see all the possibilities!

== A Python producer and consumer

This is another example of producing and consuming messages using Beam.
Instead of using curl, this example will use the "requests" Python library to issue HTTP requests.

=== Create project
. Create a new file to hold the Python code.
+
[source,shell]
----
touch beam.py
----

. Paste the following code into "beam.py".
+
[source,python]
----
include::{luna-streaming-examples-repo}/beam/produce-consume.py[]
----

=== Run example Python code
. Run the Python example (we used Python version 3.8.10).
+
[source,shell]
----
python3 beam.py
----

. The output should show 1 message was published and 1 message was consumed.
+
----
Published 1 message (200)
Consumed messages (200):
{
  "limit": 10,
  "size": 1,
  "messages": [
    {
      "payload": "SGkgdGhlcmUh",
      "topic": "persistent://public/default/my-beam-topic",
      "eventTime": "2023-01-03T15:52:24.054Z",
      "publishTime": "2023-01-03T15:52:24.054Z",
      "messageId": "&{ledgerID:16 entryID:0 batchIdx:0 partitionIdx:0 tracker:<nil> consumer:0xc002287e10}",
      "key": ""
    }
  ]
}
----

[NOTE]
====
The payload is base64 encoded. Simply decode the string to see the actual message data.
====

== Clean up
include::partial$cleanup-terminal-and-helm.adoc[]

== Next steps

Here are links to resources and guides you might be interested in:

* https://github.com/kafkaesque-io/pulsar-beam[Learn more] about the Pulsar Beam project
* https://kafkaesque-io.github.io/pulsar-beam-swagger[Pulsar Beam API]
* xref:pulsar-sql.adoc[]