= Using Starlight for Kafka with Luna Streaming
:navtitle: Starlight for Kafka with Luna Streaming
:description: This guide will take you step-by-step through deploying DataStax Luna Streaming helm chart with the Starlight for Kafka protocol handler extension
:title: A guide to deploying Luna Streaming with the Starlight for Kafka extension

Starlight for Kafka brings the native Apache Kafka protocol support to Apache Pulsar by introducing a Kafka protocol handler on Pulsar brokers. By adding the Starlight for Kafka protocol handler to your Pulsar cluster, you can migrate your existing Kafka applications and services to Pulsar without modifying the code.

== Pre-req's

You will need the following things in place to complete this guide:

* https://helm.sh/docs/intro/install/[Helm 3 cli^]{external-link-icon} (we used version 3.8.0)
* https://www.apache.org/dyn/closer.cgi?path=/kafka/3.3.1/kafka_2.13-3.3.1.tgz[Kafka cli^]{external-link-icon} (we used version3.3.1)
* Enough access to a K8s cluster to create a namespace, deployments, and pods
* https://kubernetes.io/docs/tasks/tools/[Kubectl cli^]{external-link-icon} (we used version 1.23.4)

== Install Luna Streaming helm chart

include::partial$install-helm.adoc[]

== Forward service port

We will need to interact with a few of the services in the K8s cluster. Let’s map a few ports to those services.

include::partial$port-forward-web-service.adoc[]

include::partial$port-forward-s4k.adoc[]

== Have a look around

The Luna Streaming Helm Chart automatically creates a tenant named "public" and a namespace within that tenant named "default". The Starlight for Kafka extension creates a few namespaces and topics to function correctly.

List the namespaces in the "public" tenant to see what was created.

[source,shell]
----
~/apache-pulsar-2.10.1$ ./bin/pulsar-admin namespaces list public
----

The output should be similar to the following.

[source,shell]
----
public/__kafka
public/__kafka_producerid
public/default
----

Notice the namespaces prefixed with "__kafka". These are used by the service for different functions. To learn more about Starlight for Kafka operations xref:starlight-for-kafka:ROOT:index.adoc[read the docs].

== Produce a message with the Kafka cli

If you hadn't noticed we never opened the Pulsar binary port to accept new messages. Only the admin port and the Kafka port are open. To further show how native Starlight for Kafka is, we will use the Kafka cli is produce and consume messages from Pulsar.

Assuming you are in the Kafka cli folder run the following command to start the shell.

[source,shell]
----
~/kafka_2.13-3.3.1$ ./bin/kafka-console-producer.sh --topic quickstart --bootstrap-server localhost:9092
----

Then type a message and Ctrl-C to exit the producer shell.

[source,shell]
----
This my first message
----

What a second! We never created a topic. Where did the "quickstart" topic come from?! The default behavior of Starlight for Kafka is to create a new single partition, persistent topic when not present. You can configure this and many other parameters like which tenants Starlight for Kafka can interact with, in the helm chart. Learn more about the configuration values xref:starlight-for-kafka:configuration:starlight-kafka-configuration.adoc[here].

Let's have a look at the topic that was created. From your pulsar home folder, run the following command.

[source,shell]
----
~/apache-pulsar-2.10.1$ ./bin/pulsar-admin topics list public/default
----

The output will include the new topic created.

[source,shell]
----
persistent://public/default/quickstart-partition-0
----

== Consume the new message with the Kafka cli

Now let's use the Kafka cli to consume the message we just produced. Start the consumer shell from the Kafka home folder, with the following command.

[source,shell]
----
~/kafka_2.13-3.3.1$ ./bin/kafka-console-consumer.sh --topic quickstart --from-beginning --bootstrap-server localhost:9092
----

The data of our new message will be output. You can Ctrl-C to exit the shell.

[source,shell]
----
This my first message
----

== Summary

The combination of Pulsar and Starlight for Kafka is a powerful pair! Kafka users and existing applications using Kafka can enjoy the many benefits of a Pulsar cluster while never having to change tooling or libraries. Other folks that are more confortable with Pulsar tooling and clients can also interact with the same topics. Together new and legacy applications work together to create modern solutions.

== Next steps

Here are links to other guides and resource you might be interested in.

* xref:xxxxx[Something]
* Something else