= Starlight for Luna Streaming

Starlight for Luna Streaming allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform with various connectors for Apache Pulsar®.

Starlight is open source and is included in DataStax’s https://www.datastax.com/legal/luna-streaming-supplemental-support-policy[Luna Streaming Enterprise] support for Pulsar.

== Starlight for Kafka

Starlight for Kafka brings native Apache Kafka® protocol support to Apache Pulsar by introducing a Kafka protocol handler on Pulsar brokers.

For more, see the https://docs.datastax.com/en/starlight-kafka/docs/1.0/index.html[Starlight for Kafka documentation].

== Starlight for RabbitMQ

Starlight for RabbitMQ™ combines the industry-standard AMQP 0.9.1 (RabbitMQ) API with the cloud-native and horizontally scalable Pulsar streaming platform, providing a powerful way to modernize your RabbitMQ infrastructure, improve performance, and reduce costs.

For more, see https://docs.datastax.com/en/starlight-rabbitmq/docs/1.0/getting-started.html[getting started with Starlight for RabbitMQ].

== Starlight for JMS

Starlight for JMS allows enterprises to take advantage of the scalability and resiliency of a modern streaming platform to run their existing JMS applications. Because Pulsar is open-source and cloud-native, Starlight for JMS enables enterprises to move their JMS applications to run on-premises and in any cloud environment.

For more, see https://docs.datastax.com/en/fast-pulsar-jms/docs/1.1/pulsar-jms-install.html[Starlight for JMS installation].
