= Using Starlight for RabbitMQ with Luna Streaming
:navtitle: Starlight for RabbitMQ
:description: This guide will take you step-by-step through deploying DataStax Luna Streaming helm chart with the Starlight for RabbitMQ protocol handler extension
:title: A guide to deploying Luna Streaming with the Starlight for RabbitMQ extension
:helmValuesPath: https://raw.githubusercontent.com/datastaxdevs/luna-streaming-examples/main/starlight-for-rabbitmq/values.yaml

Starlight for RabbitMQ brings the native RabbitMQ protocol support to Apache Pulsar by introducing a RabbitMQ protocol handler on Pulsar brokers or Pulsar proxies. By adding the Starlight for RabbitMQ protocol handler to your Pulsar cluster, you can migrate your existing RabbitMQ applications and services to Pulsar without modifying the code.

== Pre-req's

You will need the following things in place to complete this guide:

* https://helm.sh/docs/intro/install/[Helm 3 cli^]{external-link-icon} (we used version 3.8.0)
* Python (we used version 3.8.10)
* Enough access to a K8s cluster to create a namespace, deployments, and pods
* https://kubernetes.io/docs/tasks/tools/[Kubectl cli^]{external-link-icon} (we used version 1.23.4)

== Install Luna Streaming helm chart

include::partial$install-helm.adoc[]

== Forward service port

We will need to interact with a few of the services in the K8s cluster. Let’s map a few ports to those services.

include::partial$port-forward-web-service.adoc[]

include::partial$port-forward-s4r.adoc[]

== Produce a message with the RabbitMQ python client

If you hadn't noticed we never opened the Pulsar binary port to accept new messages. Only the admin port and the RabbitMQ port are open. To further show how native Starlight for RabbitMQ is, we will use the pika RabbitMQ python library to produce and consume messages from Pulsar.

First save the following python script to a safe place. The script assumes you have opened localhost:5672 port.

[source,python]
----
include::{luna-streaming-examples-repo}/starlight-for-rabbitmq/test-queue.py[]
----

Now open a terminal and go to your safe place. Run the following command to execute the python program.

[source,shell]
----
python ./test-queue.py
----

The output should look like the following.

[souce,shell]
----
created test-queue queue
published message test
received message: test
deleted test-queue queue
----

== Summary

Wow! That was easy. The Luna help chart took care of deploying Starlight for RabbitMQ on Pulsar proxy and opening the correct port. Now your application "talks" to Pulsar as if it were a real RabbitMQ host.

== Next steps

Here are links to other guides and resource you might be interested in.

* xref:streaming-learning:use-cases-architectures:starlight/rabbitmq/index.adoc[Messaging with Starlight for RabbitMQ]
* xref:pulsar-beam.adoc[]
* xref:pulsar-sql.adoc[]
* xref:heartbeat-vm.adoc[]