= VM-based Pulsar production cluster

This page contains sizing and configuration information for a single VM-based production cluster.
The methodology and assumptions driving these recommendations are described in xref:production-cluster-sizing.adoc[].

== Sizing analysis and calculation example

Assume a Pulsar cluster has the following workload, topology, and VM hardware characteristics:

.Workload input characteristics
[cols=2*,options=header]
|===
|*Workload input*
|*Value*

|Average message throughput
|50 K messages/second

|Average message payload size
|10 K bytes

|Message compression
|None

|Message replication factorfootnote:[This should match the number of the availability zones (see Pulsar topology information below)]
|3

|Message retention and TTL periodfootnote:[Unacknowledged messages will expire after 1 day. Acknowledged messages will continue stay in the system up to 1 day]
|1 day

|===

.Topology characteristics
[cols=2*,options=header]
|===
|*Topology requirements*
|*Value*

|Availability Zones per region (AZs)footnote:[Pulsar server instances (of the same component type) should be evenly distributed across 3 AZs as much as possible, with minimum 1 Pulsar server instance per component type.]
|3

|Required Pulsar server components
|Zookeepers, Bookkeepers, Brokers, Standalone autorecovery, Pulsar Proxy

|Broker to bookkeeper ratio
|1-to-5

|===

.VM hardware characteristics
[cols=2*,options=header]
|===
|*VM hardware specification*
|*Value*

|VM Hardware specification
|The disk space for bookkeeper is 4TB per bookkeeper server instancefootnote:[Effective bookkeeper ledger disk utilization percentage is 85%]

|===

== Sizing calculation

. Determine the Pulsar server instance counts for all required server component types.
.. Multiply replication factor by average message payload size by average message throughput.
+
[source,plain]
----
Total message size (raw) =
3 *    // replication factor: 3
10k *   // average message payload size: 10k bytes
50k * // average message throughput: 50k messages/sec
(24 * 3600)    // TTL and retention period: 1 day
    = 129,600,000 MB
    ≅ 124 TB
----
.. We now know our cluster needs 124 TB of storage for Bookkeeper ledger data, so we can calculate the number of Bookkeeper nodes with the ledger disk capacity of 4TB and an 85% effective utilization ratio.
+
[source,plain]
----
Bookkeeper count(raw)=ceiling(124/(4 * 0.85)) = 
----

With our <<assumptions,assumption>> of a 1-to-5 broker-to-bookkeeper ratio, we calculate the number of broker nodes.
+
[source,plain]
----
Broker count(raw)=ceiling(8/5) = 2
----


