:activeTopics: 250
:messageSize: 3
:messageThroughput: 350
:retentionPolicy: 3600
:ttlPolicy: 24
:tieredStoragePolicy: n/a
:messageReplicationFactor: 3

= Dev and Test VM sandbox clusters

This page sizes the minimum, baseline resources for a Pulsar cluster on VM.
Size your cluster through development and test environments starting with the recommended counts below.
The methodology and assumptions driving these recommendations are described in xref:production-cluster-sizing.adoc[].

== Development cluster

Gather these workload characteristics to determine your cluster's size requirements:

.Workload input characteristics
[cols=2*,options=header]
|===
|*Workload input*
|*Value*

| Number of active topics
| {activeTopics}

| Average message size
| {messageSize} MB

| Incoming message throughput
| {messageThroughput} messages per second

| Message retention
| {retentionPolicy} seconds

| TTL Policy
| {ttlPolicy} hours

| Tiered storage
| {tieredStoragePolicy}

|===

== Example methodology

With the aggregated workload characteristics, we can now apply our methodology to these characteristics to size a production cluster. +

First, we will size the bookkeeper's disk.
We size this first because it's the most important component (bookies store message data) and are also the hardest to scale.
By default, Pulsar sets Bookkeeper https://pulsar.apache.org/docs/2.11.x/administration-zk-bk/#bookkeeper-persistence-policies[ack-quorum] size to 2.
That means at least 2 bookies in the ensemble need to acknowledge receipt of message data before Pulsar will acknowledge receipt of the message.
But (very important) we want the message replication factor to be an odd number, so we can tolerate 1 Bookie failure.

. Multiply replication factor ({messageReplicationFactor}) by average message payload size ({messageSize}) by average message throughput ({messageThroughput}), then factor in TTL ({ttlPolicy}) and retention period ({retentionPolicy}).
+
[source,plain,subs="attributes+"]
----
Total message size (raw) =
{messageReplicationFactor} *           // replication factor
{messageSize} Kb *        // average message payload size
{messageThroughput} *      // average message throughput
({ttlPolicy} * {retentionPolicy})   // TTL and retention period
= 25,920,000 MB
≅ 25 TB
----
We now know our cluster needs 25 TB of storage for Bookkeeper ledger data.

. Calculate the number of Bookkeeper nodes with an individual ledger disk capacity.
+
[source,plain]
----
Bookkeeper count(raw)=ceiling(25/(4 * 0.85)) = 8
----
We need 8 total bookies across 3 zones. Bookies must be evenly distributed, so we adjust this to a number that is divisible by the number of zones.

. Given the replication factor of 3, we will need at least 1 broker to write messages to the bookies. That gives us a broker-to-bookkeeper ratio of 1:3. Now we can calculate the total number of Brokers across 3 zones.
+
[source,plain]
----
Broker count(raw)=ceiling(8/3) = 3
----
We will need 3 Brokers (one in each Zone) to serve messages. This should also be evenly divisible by the number of zones.


== Development cluster
.Development cluster sizing
[cols=4*,options=header]
|===
|Environment
|Server Component
|Node Count
|Note

|DEV
|(combined) Zookeeper, Broker, and Bookie
|3
|1 node per AZ +
In the simplest case, Pulsar can run on only 1 server host as a standalone mode.
|===

.Development Cluster hardware
[cols=4*,options=header]
|===
|Environment
|Server Component
|Hardware Spec
|Note

|DEV
|(Combined)  Zookeeper, Broker, and Bookkeeper
a|* CPU: 8 vCPU +
* Memory: 16 GB
* Data Disk: 64 GB SSD
a|Data disks are shared by: +
* zookeeper data +
* bookkeeper journal +
* bookkeeper ledger
|===

== Test cluster

.Test cluster sizing
[cols=4*,options=header]
|===
|Environment
|Server Component
|Node Count
|Note

.4+|TEST
|Zookeeper
|3
|1 node per AZ
| (Combined) Broker and Function Worker
| 3
| 1 node per AZ +
Even if the Pulsar function is needed, it runs as part of the brokers. No dedicated function worker node is needed.
| Bookie
| 6
| 2 nodes per AZ +
See note 3 below
| Admin Console and Heartbeat
| 1
| Shared 1 server host; placed in any rack
|===

.Test Cluster hardware
[cols=4*,options=header]
|===
|Environment
|Server Component
|Hardware Spec
|Note

.4+|TEST
|Zookeeper
a|* CPU: 2 vCPU +
* Memory: 4 GB
* Data Disk: 32 GB SSD
|
|(Combined) Broker and Function Worker
a|* CPU: 8 vCPU +
* Memory: 16 GB
|No data disk
|Bookie
a|* CPU: 4 vCPU +
* Memory: 16 GB +
* Data Disk +
** Journal: 32 GB SSD +
** Ledger: 256 GB SSD
|
|(combined) AdminConsole and Heartbeat
a|* CPU: 4 vCPU +
* Memory: 8 GB
|
|===

== What's next?

See more production-ready sizing examples for the following scenarios:

* xref:production-cluster-sizing.adoc[]
* xref:production-cluster-multiregion.adoc[]
