:activeTopics: 100
:messageSize: 1MB
:messageThroughput: 5000 messages per second
:retentionPolicy: 1 month
:ttlPolicy: 1 month
:tieredStoragePolicy: n/a
:messageReplicationFactor: 3

= Pulsar VM sandbox cluster

Want to take a cluster for a spin, but don't need to size for production just yet?
This page sizes the minimum, baseline resources for a Pulsar cluster on VM.
Instead of 3 Brokers, 3 Bookies, and 3 Zookeepers for a 3/3/3 production cluster on VM, this cluster has 1 of each for a 3 VM cluster.

The methodology and assumptions driving these recommendations are described in xref:production-cluster-sizing.adoc[].

.Development cluster sizing
[cols=4*,options=header]
|===
|Environment
|Server Component
|Node Count
|Note

|DEV
|(combined) Zookeeper, Broker, and Bookie
|3
|1 node per AZ +
In the simplest case, Pulsar can run on only 1 server host as a standalone mode.
|===

.Development Cluster hardware
[cols=4*,options=header]
|===
|Environment
|Server Component
|Hardware Spec
|Note

|DEV
|(Combined)  Zookeeper, Broker, and Bookkeeper
a|* CPU: 8 vCPU +
* Memory: 16 GB
* Data Disk: 64 GB SSD
a|Data disks are shared by: +
* zookeeper data +
* bookkeeper journal +
* bookkeeper ledger
|===

== What's next?

See more production-ready sizing examples for the following scenarios:

* xref:production-cluster-sizing.adoc[]
* xref:production-cluster-multiregion.adoc[]
* xref:production-cluster-vm.adoc[]
