== Multi-tenancy in Pulsar

Pulsar was created with support for multi-tenancy.
Multi-tenant systems run isolated workloads on shared hardware. For example, when provisioning multiple customers' applications on the same datacenter, a multi-tenant system must meet each customer's security, isolation, and performance requirements, while minimizing the impact they have on each other's workloads.

Pulsar provisions resources to a *tenant*. A tenant can contain multiple *namespaces*. Namespaces administrate all *topics* within them. This structure is built into the Pulsar persistent topic URL:
[source,shell]
----
persistent://tenant/namespace/topic
----

Each tenant has its own <<Security context>>, <<Resource utilization>>, and <<Isolation policies>>.

[#security-context]
=== Security context

Security context on a Pulsar tenant protects message data from being accessed by unauthorized users, including those from other tenants in your organization.

==== Cluster administrator
Set the following configuration parameters in your Pulsar cluster's `broker.conf` file:
[source,shell]
----
authorizationEnabled=true
authorizationProvider=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider
authorizationAllowWildcardsMatching=[true|false]
superUserRoles=<list of role names>
----

The `superUserRoles` parameter accepts a comma-separated list of role names. The identified roles can manage tenants, namespaces, and topics.

==== Tenant administrator

The cluster administrator can create tenants with a list of assigned tenant administrators:

[source,shell]
----
pulsar-admin tenants create <tenant-name> \
    --allowed clusters <list of allowed clusters> \
    --admin-roles <list of admin role names>
----

The `admin-roles` parameter accepts a comma-separated list of role names. The identified roles can manage namespaces and topics within the created tenant.

==== Namespace and topic access control
The tenant administrator can define access control privileges within the tenant at both the namespace and topic level:

[tabs]
====
Namespace::
+
--
[source,shell]
----
pulsar-admin namespaces grant-permission <tenant>/<namespace> \
    --role <role_name> \
    --actions [produce|consume|produce,consume]
----
--
+
Topic::
+
--
[source,shell]
----
pulsar-admin topics grant-permission persistent://<tenant>/<namespace>/<topic> \
    --role <role_name> \
    --actions [produce|consume|produce,consume]
----
--
====

When applied at the *namespace* level, the role has privileges to produce and consume messages on all topics within the namespace.
When applied at the *topic* level, the role has privileges to produce and consume messages only on the specified topic.

[#resource-utilization]
=== Resource utilization



[#isolation-policies]
=== Isolation policies