= Multi-tenancy in Pulsar

Pulsar was created with support for multi-tenancy.
Multi-tenant systems run isolated workloads on shared hardware.
For example, when provisioning multiple customers' applications on the same datacenter, a multi-tenant system must meet each customer's security, isolation, and performance requirements, while minimizing the impact they have on each other's workloads.

Pulsar provisions resources to a *tenant*.
A tenant can contain multiple *namespaces*.
Namespaces administrate all *topics* within them.
This structure is built into the Pulsar persistent topic URL:
[source,shell]
----
persistent://tenant/namespace/topic
----

Each tenant has its own <<Security context>>, <<Resource utilization>>, and <<Isolation policies>>.

[#security-context]
== Security context

Security context on a Pulsar tenant protects message data from being accessed by unauthorized users, including those from other tenants in your organization.

=== Cluster administrator role
Set the following configuration parameters in your Pulsar cluster's `broker.conf` file:
[source,shell]
----
authorizationEnabled=true
authorizationProvider=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider
authorizationAllowWildcardsMatching=[true|false]
superUserRoles=<list of role names>
----

The `superUserRoles` parameter accepts a comma-separated list of role names. The identified roles can manage tenants, namespaces, and topics.

=== Tenant administrator role

The cluster administrator can create tenants with a list of assigned tenant administrators:

[source,shell]
----
pulsar-admin tenants create <tenant-name> \
    --allowed clusters <list of allowed clusters> \
    --admin-roles <list of admin role names>
----

The `admin-roles` parameter accepts a comma-separated list of role names. The identified roles can manage namespaces and topics within the created tenant.

=== Namespace and topic access control
The tenant administrator can define access control privileges within the tenant at both the namespace and topic level:

[tabs]
====
Namespace::
+
--
[source,shell]
----
pulsar-admin namespaces grant-permission <tenant>/<namespace> \
    --role <role_name> \
    --actions [produce|consume|produce,consume]
----
--
+
Topic::
+
--
[source,shell]
----
pulsar-admin topics grant-permission persistent://<tenant>/<namespace>/<topic> \
    --role <role_name> \
    --actions [produce|consume|produce,consume]
----
--
====

When applied at the *namespace* level, the role has privileges to produce and consume messages on all topics within the namespace.
When applied at the *topic* level, the role has privileges to produce and consume messages only on the specified topic.

[#resource-utilization]
== Resource utilization

There are many policies available for controlling resources in Pulsar.
A full list of commands and configurations is available in the https://pulsar.apache.org/docs/2.10.x/pulsar-admin/[Pulsar admin CLI documentation].
Resource policies are set at the namespace or topic levels via the pulsar-admin CLI or REST APIs, or managed more directly by setting *resource quotas*.

=== Individual topic message rate
[source,shell]
----
pulsar-admin topics set-publish-rate persistent://tenant/namespace/topic \
    --byte-publish-rate <byte_rate_number> \
    --msg-publish-rate <msg_rate_number>
----

=== Namespace bundle quota
[source,shell]
----
pulsar-admin resource-quotas set \
    --namespace <namespace_name> \
    --bundle <bundle_range> \
    --bandwidthIn <incoming_message_bytes_number>
    --bandwidthOut <outcoming_message_bytes_number> \
    --msgRateIn <outcoming_message_number> \
    --msgRateOut <incoming_message_number> \
    --memory <message_usage_number> \
    --dynamic <whether or not to allow dynamic re-calculation>
----

=== Namespace level quota
[source,shell]
----
pulsar-admin namespaces set-publish-rate tenant/namespace \
    --byte-publish-rate <byte_rate_number> \
    --msg-publish-rate <msg_rate_number>
----

=== Number of producers and consumers per topic

Set a namespace-level resource quota to limit the maximum consumers per topic:
[source,shell]
----
pulsar-admin namespaces set-max-consumers-per-topic tenant/namespace \
    --max-consumers-per-topic <consumer_number>
----

Set a topic-level resource quota to limit the maximum number of producers to a topic:
[source,shell]
----
pulsar-admin topics set-max-producers persistent://tenant/namespace/topic \
    --max-producers <producer_number>
----

More examples are available in the https://pulsar.apache.org/docs/2.10.x/pulsar-admin/[Pulsar admin CLI documentation].

[#isolation-policies]
== Isolation policies

https://pulsar.apache.org/docs/2.10.x/pulsar-admin/#ns-isolation-policy[Namespace isolation policies]